create table if not exists public.professional_leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  title text not null,
  city text not null,
  phone text not null,
  email text not null,
  registration text,
  linkedin text,
  slug text not null unique,
  profile_json jsonb not null,
  status text not null default 'novo',
  password_hash text,
  password_salt text
);
create index if not exists professional_leads_created_at_idx on public.professional_leads (created_at desc);
create index if not exists professional_leads_slug_idx on public.professional_leads (slug);
alter table public.professional_leads enable row level security;
