import type { VercelRequest,VercelResponse } from "@vercel/node";
import {createHmac,timingSafeEqual,scryptSync} from "node:crypto";
const url=process.env.SUPABASE_URL;const service=process.env.SUPABASE_SERVICE_ROLE_KEY;
function out(res:VercelResponse,status:number,body:unknown){return res.status(status).setHeader("Content-Type","application/json").setHeader("Cache-Control","no-store").json(body)}
function clean(v:unknown,max=500){return String(v??"").trim().slice(0,max)}
function normalizePhone(v:string){return v.replace(/\\D/g,"").replace(/^55/,"")}
function normalizeLinkedin(value:string){const v=value.trim();if(!v)return "";if(/^linkedin\\.com\\//i.test(v))return `https://www.${v}`;if(/^www\\.linkedin\\.com\\//i.test(v))return `https://${v}`;return v}
function normalize(body:any,current:any){const p=body.profile||{};const skills=Array.isArray(p.skills)?p.skills.map((x:any)=>clean(x,80)).filter(Boolean).slice(0,20):[];const projects=Array.isArray(p.projects)?p.projects.slice(0,6).map((x:any,i:number)=>({title:clean(x?.title,120)||`Projeto ${i+1}`,location:clean(x?.location,120),role:clean(x?.role,600),result:clean(x?.result,300),images:Array.isArray(x?.images)?x.images.filter((u:any)=>typeof u==="string"&&u.startsWith("https://")).slice(0,2):[]})):[];return {...current,name:clean(p.name,120)||current.name,title:clean(p.title,120)||current.title,location:clean(p.location,120),registration:clean(p.registration,120),headline:clean(p.headline,180),summary:clean(p.summary,2000),phone:clean(p.phone,40),linkedin:normalizeLinkedin(clean(p.linkedin,300)),avatarUrl:typeof p.avatarUrl==="string"&&p.avatarUrl.startsWith("https://")?p.avatarUrl:"",skills,projects}}
function secret(){return service||""}
function sign(payload:string){return createHmac("sha256",secret()).update(payload).digest("base64url")}
function makeToken(id:string,email:string){const payload=Buffer.from(JSON.stringify({id,email,exp:Date.now()+24*60*60*1000})).toString("base64url");return `${payload}.${sign(payload)}`}
function readToken(value:string){try{const [payload,sig]=value.split(".");if(!payload||!sig||!secret())return null;const expected=sign(payload);if(sig.length!==expected.length||!timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;const data=JSON.parse(Buffer.from(payload,"base64url").toString("utf8"));if(!data.id||!data.email||data.exp<Date.now())return null;return data}catch{return null}}
async function db(path:string,init:RequestInit={}){if(!url||!service)throw new Error("Banco não configurado.");return fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:service,Authorization:`Bearer ${service}`,"Content-Type":"application/json",...(init.headers||{})}})}
function validPassword(password:string,salt:string,hash:string){try{const derived=scryptSync(password,salt,64).toString("hex");return derived.length===hash.length&&timingSafeEqual(Buffer.from(derived),Buffer.from(hash))}catch{return false}}
async function findById(id:string){const r=await db(`professional_leads?id=eq.${encodeURIComponent(id)}&select=id,slug,profile_json,status,email,phone,password_hash,password_salt&limit=1`);if(!r.ok)return null;const rows=await r.json();return rows[0]||null}
export default async function handler(req:VercelRequest,res:VercelResponse){try{
 if(req.method==="POST"){const email=clean(req.body?.email,160).toLowerCase();const password=String(req.body?.password||"");if(!email||!password)return out(res,400,{error:"Informe o e-mail e a senha cadastrados."});const found=await db(`professional_leads?email=eq.${encodeURIComponent(email)}&select=id,slug,profile_json,status,email,password_hash,password_salt&limit=1`);if(!found.ok)return out(res,500,{error:"Não foi possível localizar o perfil."});const rows=await found.json();const lead=rows[0];if(!lead||lead.status==="arquivado"||!lead.password_hash||!lead.password_salt||!validPassword(password,String(lead.password_salt),String(lead.password_hash)))return out(res,401,{error:"E-mail ou senha incorretos."});return out(res,200,{slug:lead.slug,profile:lead.profile_json,editToken:makeToken(lead.id,email)})}
 if(req.method==="GET"){return out(res,405,{error:"Use o acesso por e-mail e WhatsApp para abrir a edição."})}
 if(req.method==="PUT"){const token=String(req.headers["x-edit-token"]||"");const auth=readToken(token);if(!auth)return out(res,401,{error:"Sua sessão de edição expirou. Informe novamente seus dados."});const lead=await findById(auth.id);if(!lead||String(lead.email).toLowerCase()!==auth.email||lead.status==="arquivado")return out(res,401,{error:"Sessão de edição inválida."});const profile=normalize(req.body,lead.profile_json);const update=await db(`professional_leads?id=eq.${lead.id}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({name:profile.name,title:profile.title,city:profile.location,phone:profile.phone,linkedin:profile.linkedin,registration:profile.registration,profile_json:profile})});if(!update.ok)return out(res,500,{error:"Não foi possível salvar as alterações."});return out(res,200,{slug:lead.slug,profile})}
 return out(res,405,{error:"Método não permitido."})
}catch(e){return out(res,500,{error:e instanceof Error?e.message:"Erro interno."})}}