import {useState} from "react";
import {Button} from "../components/ui/button";
export default function LeadsAdminPage(){
 const [key,setKey]=useState(""); const [leads,setLeads]=useState<any[]|null>(null); const [error,setError]=useState("");
 async function load(){setError("");const r=await fetch("/api/leads",{headers:{"x-admin-key":key}});const data=await r.json();if(!r.ok){setError(data.error||"Acesso negado.");return}setLeads(data)}
 return <main className="min-h-screen bg-[#F5F1E9] text-[#0B3047]"><header className="bg-[#0B3047] px-5 py-5 text-white"><div className="mx-auto max-w-6xl flex items-center justify-between"><strong className="font-display text-2xl">NEGÓCIO FECHADO · LEADS</strong><a href="/#/criar-perfil" className="text-sm underline">Ver cadastro</a></div></header>
 <div className="mx-auto max-w-6xl px-5 py-10"><h1 className="font-display text-5xl font-semibold">Profissionais captados</h1><p className="mt-2 text-[#5E6870]">Acompanhe os profissionais que entraram pelo seu formulário.</p>
 {!leads?<div className="mt-8 max-w-md rounded-2xl border border-[#D7D0C4] bg-[#FFFDF9] p-6"><label className="text-sm font-semibold">Chave administrativa</label><input className="mt-2 w-full rounded-xl border border-[#D7D0C4] bg-white px-4 py-3" type="password" value={key} onChange={e=>setKey(e.target.value)} /><Button className="mt-4 w-full bg-[#F15A24]" onClick={()=>void load()}>Entrar</Button>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}</div>:<div className="mt-8 overflow-x-auto rounded-2xl border border-[#D7D0C4] bg-[#FFFDF9]"><table className="w-full text-left text-sm"><thead><tr className="border-b border-[#D7D0C4]"><th className="p-4">Profissional</th><th className="p-4">Área</th><th className="p-4">Cidade</th><th className="p-4">Contato</th><th className="p-4">Status</th></tr></thead><tbody>{leads.map(x=><tr key={x.id} className="border-b border-[#D7D0C4] last:border-0"><td className="p-4 font-semibold">{x.name}</td><td className="p-4">{x.title}</td><td className="p-4">{x.city}</td><td className="p-4"><a className="underline" href={`https://wa.me/55${String(x.phone).replace(/\\D/g,"")}`}>{x.phone}</a><br/><a className="underline" href={`mailto:${x.email}`}>{x.email}</a></td><td className="p-4">{x.status}</td></tr>)}</tbody></table></div>}</div></main>
}
