import {useState} from "react";
import {ImagePlus,X} from "lucide-react";
import {Button} from "../components/ui/button";import {Card,CardContent} from "../components/ui/card";import {Input} from "../components/ui/input";import {Label} from "../components/ui/label";import {Textarea} from "../components/ui/textarea";
type Photo={file:File;preview:string};
export default function ProfessionalSignupPage(){
 const[form,setForm]=useState({name:"",title:"",city:"",phone:"",email:"",registration:"",linkedin:"",headline:"",summary:"",skills:""});const[avatar,setAvatar]=useState<Photo|null>(null);const[portfolio,setPortfolio]=useState<Photo[]>([]);const[error,setError]=useState("");const[loading,setLoading]=useState(false);
 const set=(key:string,value:string)=>setForm(x=>({...x,[key]:value}));
 const pickAvatar=(file?:File)=>{if(file&&file.type.startsWith("image/"))setAvatar({file,preview:URL.createObjectURL(file)})};
 const pickPortfolio=(files:FileList|null)=>{if(!files)return;setPortfolio(x=>[...x,...Array.from(files).filter(f=>f.type.startsWith("image/")).slice(0,6-x.length).map(file=>({file,preview:URL.createObjectURL(file)}))])};
 const upload=async(file:File)=>{const dataUrl=await resizeImage(file);const r=await fetch("/api/upload",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({dataUrl,filename:file.name})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Não foi possível enviar a imagem.");return data.url as string};
 async function submit(e:React.FormEvent){e.preventDefault();setError("");setLoading(true);try{const avatarUrl=avatar?await upload(avatar.file):"";const portfolioImages=[] as string[];for(const item of portfolio)portfolioImages.push(await upload(item.file));const r=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,avatarUrl,portfolioImages})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Não foi possível cadastrar.");location.href=`/perfil/${data.slug}`}catch(e){setError(e instanceof Error?e.message:"Erro ao cadastrar.");setLoading(false)}}
 return <main className="min-h-screen bg-[#F5F1E9] text-[#0B3047]"><div className="bg-[#0B3047] px-5 py-2 text-center font-mono text-[10px] uppercase tracking-[.16em] text-white">Negócio Fechado · Cadastro profissional</div><div className="mx-auto max-w-3xl px-5 py-12 md:py-20"><p className="font-mono text-[10px] font-bold uppercase tracking-[.2em] text-[#F15A24]">Seu espaço profissional</p><h1 className="mt-3 font-display text-6xl font-semibold leading-none md:text-7xl">Crie seu perfil profissional.</h1><p className="mt-5 max-w-2xl text-lg leading-7 text-[#5E6870]">Apresente seu trabalho, serviços e contatos em uma página profissional gratuita do Negócio Fechado.</p><Card className="mt-10 rounded-3xl border-[#D7D0C4] shadow-none bg-[#FFFDF9]"><CardContent className="p-6 md:p-9"><form onSubmit={submit} className="space-y-8">
 <div><Label>Foto de perfil</Label><div className="mt-3 flex items-center gap-5">{avatar?<div className="relative"><img src={avatar.preview} className="h-24 w-24 rounded-full object-cover" alt="Prévia da foto"/><button type="button" onClick={()=>setAvatar(null)} className="absolute -right-1 -top-1 rounded-full bg-[#0B3047] p-1 text-white"><X size={14}/></button></div>:<label className="flex h-24 w-24 cursor-pointer flex-col items-center justify-center rounded-full border-2 border-dashed border-[#D7D0C4] text-[#5E6870]"><ImagePlus size={20}/><span className="mt-1 text-[10px]">Adicionar</span><input type="file" accept="image/*" className="hidden" onChange={e=>pickAvatar(e.target.files?.[0])}/></label>}<p className="max-w-xs text-xs leading-5 text-[#5E6870]">Use uma foto profissional. A imagem será otimizada antes do envio.</p></div></div>
 <div className="grid gap-5 md:grid-cols-2"><Field label="Nome completo *" value={form.name} onChange={v=>set("name",v)}/><Field label="Profissão / especialidade *" value={form.title} onChange={v=>set("title",v)}/><Field label="Cidade / região *" value={form.city} onChange={v=>set("city",v)}/><Field label="WhatsApp *" value={form.phone} onChange={v=>set("phone",v)}/><Field label="E-mail *" type="email" value={form.email} onChange={v=>set("email",v)}/><Field label="Registro profissional" value={form.registration} onChange={v=>set("registration",v)}/></div>
 <Field label="LinkedIn" value={form.linkedin} onChange={v=>set("linkedin",v)}/><Field label="Frase de apresentação" value={form.headline} onChange={v=>set("headline",v)}/><div><Label>Sobre você</Label><Textarea className="mt-2 min-h-32" value={form.summary} onChange={e=>set("summary",e.target.value)} placeholder="Conte brevemente sobre sua experiência e atuação."/></div><div><Label>Competências</Label><Input className="mt-2" value={form.skills} onChange={e=>set("skills",e.target.value)} placeholder="Ex.: orçamento, obras, elétrica, projetos"/></div>
 <div><Label>Fotos do portfólio</Label><p className="mt-1 text-xs text-[#5E6870]">Adicione até 6 imagens dos seus projetos ou trabalhos.</p><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3">{portfolio.map((x,i)=><div key={x.preview} className="relative aspect-square overflow-hidden rounded-xl bg-[#E9E5DC]"><img src={x.preview} alt="" className="h-full w-full object-cover"/><button type="button" onClick={()=>setPortfolio(p=>p.filter((_,j)=>j!==i))} className="absolute right-2 top-2 rounded-full bg-[#0B3047] p-1 text-white"><X size={14}/></button></div>)}{portfolio.length<6&&<label className="flex aspect-square cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-[#D7D0C4] text-[#5E6870]"><ImagePlus size={24}/><span className="mt-2 text-xs">Adicionar fotos</span><input type="file" accept="image/*" multiple className="hidden" onChange={e=>pickPortfolio(e.target.files)}/></label>}</div></div>
 {error&&<p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<Button type="submit" disabled={loading} className="w-full bg-[#F15A24] py-3">{loading?"Publicando fotos e perfil...":"Criar meu perfil grátis"}</Button><p className="text-center text-xs text-[#5E6870]">Ao enviar, você concorda em fornecer seus dados para criação e gestão do perfil profissional.</p>
 </form></CardContent></Card></div></main>
}
async function resizeImage(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=1600;const scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext("2d");if(!ctx)return reject(new Error("Não foi possível processar a imagem."));ctx.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.82))};img.onerror=()=>reject(new Error("Imagem inválida."));img.src=String(reader.result)};reader.onerror=()=>reject(new Error("Não foi possível ler a imagem."));reader.readAsDataURL(file)})}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <div><Label>{label}</Label><Input type={type} className="mt-2" value={value} onChange={e=>onChange(e.target.value)} required={label.includes("*")}/></div>}