import {ArrowUpRight,BriefcaseBusiness,ExternalLink,Linkedin,Mail,MapPin,Phone,Share2} from "lucide-react";
import {useEffect,useState} from "react"; import {Button} from "../components/ui/button"; import {Card,CardContent} from "../components/ui/card"; import {loadProfile,type ProfessionalProfile} from "../data/professionalProfiles";
export default function ProfilePage(){const [profile,setProfile]=useState<ProfessionalProfile>(()=>loadProfile()); useEffect(()=>{const r=()=>setProfile(loadProfile());addEventListener("profile-updated",r);return()=>removeEventListener("profile-updated",r)},[]);
const share=async()=>{const url=location.href;if(navigator.share)await navigator.share({title:`${profile.name} — ${profile.title}`,text:profile.headline,url});else{await navigator.clipboard?.writeText(url);alert("Link copiado.")}};
const whatsapp=`https://wa.me/55${profile.phone.replace(/\\D/g,"")}?text=${encodeURIComponent("Olá Diego, vi seu perfil profissional no Negócio Fechado e gostaria de conversar.")}`;
return <main className="min-h-screen bg-[#F5F1E9] text-[#0B3047]"><div className="bg-[#0B3047] px-5 py-2 text-center font-mono text-[10px] uppercase tracking-[.16em] text-white">Negócio Fechado · Perfil profissional</div>
<header className="sticky top-0 z-20 border-b border-[#D7D0C4] bg-[#FFFDF9]/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><strong className="font-display text-2xl">NEGÓCIO FECHADO</strong><div className="flex gap-2"><a href="/#/criar-perfil"><Button className="bg-[#F15A24]">Criar meu perfil</Button></a><Button variant="outline" onClick={()=>void share()}><Share2 size={16}/>Compartilhar</Button></div></div></header>
<section className="border-b border-[#D7D0C4] bg-[#FFFDF9]"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-14 md:grid-cols-[1.2fr_.8fr] md:items-end md:py-20"><div><div className="mb-6 flex items-center gap-4">{profile.avatarUrl?<img src={profile.avatarUrl} alt={profile.name} className="h-20 w-20 rounded-full object-cover"/>:<div className="flex h-20 w-20 items-center justify-center rounded-full bg-[#0B3047] font-display text-3xl text-white">{profile.initials}</div>}<p className="font-mono text-[10px] font-bold uppercase tracking-[.17em] text-[#F15A24]">{profile.registration}</p></div><h1 className="font-display text-6xl font-semibold leading-[.9] tracking-[-.06em] md:text-8xl">{profile.name}</h1><p className="mt-4 text-2xl font-semibold">{profile.title}</p><p className="mt-2 max-w-2xl text-lg text-[#5E6870]">{profile.headline}</p><div className="mt-6 flex flex-wrap gap-5 text-sm text-[#5E6870]"><span className="flex items-center gap-2"><MapPin size={16}/>{profile.location}</span><span className="flex items-center gap-2"><Phone size={16}/>{profile.phone}</span></div><div className="mt-8 flex gap-3"><a href={whatsapp}><Button className="bg-[#F15A24]">Falar comigo</Button></a>{profile.linkedin&&<a href={profile.linkedin} target="_blank"><Button variant="outline"><Linkedin size={16}/>LinkedIn</Button></a>}</div></div><div className="relative flex min-h-72 items-end rounded-3xl bg-gradient-to-br from-[#d3e2e6] via-[#d9d2c4] to-[#8d543e] p-7 shadow-xl"><div className="bg-[#0B3047] p-5 text-white"><p className="font-mono text-[9px] uppercase tracking-[.18em] text-[#F4AE77]">ENGENHARIA CIVIL</p><p className="mt-2 font-display text-3xl font-semibold">Projeto • Gestão • Resultado</p></div></div></div></section>
<div className="mx-auto max-w-6xl px-5 py-14"><section className="grid gap-px border border-[#D7D0C4] sm:grid-cols-2 lg:grid-cols-4">{profile.highlights.map(x=><Card key={x.label} className="rounded-none border-0 bg-[#F5F1E9] shadow-none"><CardContent className="p-6"><p className="font-display text-4xl font-semibold">{x.value}</p><p className="mt-2 font-mono text-[9px] uppercase tracking-[.14em] text-[#5E6870]">{x.label}</p></CardContent></Card>)}</section>
<section className="mt-16 grid gap-12 lg:grid-cols-[1.35fr_.65fr]"><div><Eyebrow t="Sobre"/><h2 className="font-display text-5xl font-semibold">Quem sou</h2><p className="mt-6 leading-8 text-[#5E6870]">{profile.summary}</p></div><div><Eyebrow t="Competências"/><div className="mt-5 flex flex-wrap gap-2">{profile.skills.map(x=><span key={x} className="border border-[#D7D0C4] bg-[#FFFDF9] px-3 py-2 text-xs font-semibold">{x}</span>)}</div></div></section>
<section className="mt-20"><Eyebrow t="Portfólio"/><h2 className="font-display text-5xl font-semibold">Projetos em destaque</h2><div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{profile.projects.map(p=><Card key={p.title} className="overflow-hidden rounded-2xl border-[#D7D0C4] shadow-none"><CardContent className="p-7"><BriefcaseBusiness className="text-[#F15A24]"/><h3 className="mt-8 font-display text-2xl font-semibold">{p.title}</h3><p className="mt-2 font-mono text-[9px] uppercase tracking-[.14em] text-[#F15A24]">{p.location}</p><p className="mt-5 text-sm leading-6 text-[#5E6870]">{p.role}</p>{p.result&&<p className="mt-5 border-l-2 border-[#F15A24] pl-3 text-xs font-semibold">{p.result}</p>}</CardContent></Card>)}</div></section>
<section className="mt-20"><Eyebrow t="Experiência"/><h2 className="font-display text-5xl font-semibold">Trajetória profissional</h2><div className="mt-8 space-y-6">{profile.experience.map(x=><Card key={x.company} className="rounded-2xl border-[#D7D0C4] shadow-none"><CardContent className="p-7 md:grid md:grid-cols-[180px_1fr] md:gap-8"><p className="font-mono text-[9px] uppercase tracking-[.14em] text-[#F15A24]">{x.period}</p><div><h3 className="font-display text-2xl font-semibold">{x.company}</h3><p className="mt-1 text-sm font-semibold">{x.role}</p><ul className="mt-5 space-y-2 text-sm leading-6 text-[#5E6870]">{x.bullets.map(b=><li key={b}>• {b}</li>)}</ul></div></CardContent></Card>)}</div></section>
<section className="mt-20 grid gap-6 md:grid-cols-2"><Card className="rounded-2xl bg-[#0B3047] text-white"><CardContent className="p-8"><Eyebrow t="Formação" light/><h3 className="mt-4 font-display text-3xl">Engenharia Civil — UFCG</h3><p className="mt-1 text-sm text-white/70">Graduado em 2021</p><h3 className="mt-7 font-display text-2xl">Construction Management — Columbia University</h3><p className="mt-1 text-sm text-white/70">Especialização em Gerenciamento de Construções</p></CardContent></Card><Card className="rounded-2xl border-[#D7D0C4] shadow-none"><CardContent className="p-8"><Eyebrow t="Contato profissional"/><a className="mt-6 flex gap-3 font-semibold" href={`mailto:${profile.email}`}><Mail size={16}/>{profile.email}</a><a className="mt-4 flex gap-3 font-semibold" href={whatsapp}><Phone size={16}/>{profile.phone} · WhatsApp</a>{profile.linkedin&&<a className="mt-4 flex gap-3 font-semibold" href={profile.linkedin}><Linkedin size={16}/>LinkedIn</a>}<p className="mt-4 flex gap-3 text-sm text-[#5E6870]"><MapPin size={16}/>{profile.location}</p><p className="mt-5 flex gap-2 font-mono text-[9px] uppercase tracking-[.12em] text-[#F15A24]"><ExternalLink size={14}/>Perfil profissional</p></CardContent></Card></section></div></main>}
function Eyebrow({t,light=false}:{t:string;light?:boolean}){return <p className={`font-mono text-[9px] font-bold uppercase tracking-[.2em] ${light?"text-[#F4AE77]":"text-[#F15A24]"}`}>{t}</p>}
