import {useState} from "react";
import {ImagePlus,X,ArrowLeft,Plus,Trash2,Upload,CheckCircle2} from "lucide-react";
import {Button} from "../components/ui/button";import {Card,CardContent} from "../components/ui/card";import {Input} from "../components/ui/input";import {Label} from "../components/ui/label";import {Textarea} from "../components/ui/textarea";
type Photo={file:File;preview:string};type Project={title:string;location:string;description:string;photos:Photo[]};
const blank=():Project=>({title:"",location:"",description:"",photos:[]});
export default function ProfessionalSignupPage(){
 const[form,setForm]=useState({name:"",title:"",city:"",phone:"",email:"",registration:"",linkedin:"",headline:"",summary:"",skills:""});const[avatar,setAvatar]=useState<Photo|null>(null);const[projects,setProjects]=useState<Project[]>([blank()]);const[error,setError]=useState("");const[loading,setLoading]=useState(false);const[progress,setProgress]=useState("");
 const set=(key:string,value:string)=>setForm(x=>({...x,[key]:value}));
 const pickAvatar=(file?:File)=>{if(file&&file.type.startsWith("image/")){if(avatar)URL.revokeObjectURL(avatar.preview);setAvatar({file,preview:URL.createObjectURL(file)})}};
 const addProject=()=>{if(projects.length<6)setProjects(x=>[...x,blank()])};
 const updateProject=(i:number,key:keyof Omit<Project,"photos">,value:string)=>setProjects(x=>x.map((p,j)=>j===i?{...p,[key]:value}:p));
 const addPhotos=(i:number,files:FileList|null)=>{if(!files)return;const next=Array.from(files).filter(f=>f.type.startsWith("image/")).slice(0,2-projects[i].photos.length).map(file=>({file,preview:URL.createObjectURL(file)}));setProjects(x=>x.map((p,j)=>j===i?{...p,photos:[...p.photos,...next]}:p))};
 const removePhoto=(pi:number,ii:number)=>setProjects(x=>x.map((p,j)=>{if(j!==pi)return p;URL.revokeObjectURL(p.photos[ii].preview);return {...p,photos:p.photos.filter((_,k)=>k!==ii)}}));
 const upload=async(file:File)=>{const dataUrl=await resizeImage(file);const r=await fetch("/api/upload",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({dataUrl,filename:file.name})});let d:any={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||"Não foi possível enviar a imagem.");return d.url as string};
 async function submit(e:React.FormEvent){e.preventDefault();setError("");setLoading(true);try{let total=(avatar?1:0)+projects.reduce((n,p)=>n+p.photos.length,0),done=0;let avatarUrl="";if(avatar){setProgress(`Enviando imagem ${++done} de ${total}...`);avatarUrl=await upload(avatar.file)}const payloadProjects=[];for(const p of projects){if(!p.title&&!p.description&&!p.photos.length)continue;const images=[];for(const photo of p.photos){setProgress(`Enviando projeto ${p.title||"novo"} · imagem ${++done} de ${total}...`);images.push(await upload(photo.file))}payloadProjects.push({title:p.title,location:p.location,description:p.description,images})}setProgress("Publicando seu perfil...");const r=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,avatarUrl,projects:payloadProjects})});let d:any={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||"Não foi possível cadastrar.");location.href=`/perfil/${d.slug}`}catch(e){setError(e instanceof Error?e.message:"Erro ao cadastrar.");setLoading(false);setProgress("")}}
 return <main className="min-h-screen bg-[#F5F1E9] text-[#0B3047]"><div className="bg-[#0B3047] px-5 py-2 text-center font-mono text-[10px] uppercase tracking-[.16em] text-white">Negócio Fechado · Cadastro profissional</div><header className="border-b border-[#D7D0C4] bg-[#FFFDF9]"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-4"><a href="/" className="flex items-center gap-2 text-sm font-semibold"><ArrowLeft size={16}/> Voltar</a><span className="text-xs text-[#5E6870]">Publicação gratuita</span></div></header>
 <div className="mx-auto max-w-4xl px-5 py-10 md:py-16"><p className="font-mono text-[10px] font-bold uppercase tracking-[.2em] text-[#F15A24]">Seu espaço profissional</p><h1 className="mt-3 font-display text-5xl font-semibold leading-none md:text-7xl">Crie seu perfil profissional.</h1><p className="mt-5 max-w-2xl text-lg leading-7 text-[#5E6870]">Apresente quem você é e transforme cada trabalho em um projeto visual. Seu perfil sai pronto para compartilhar.</p>
 <Card className="mt-8 rounded-3xl border-[#D7D0C4] bg-[#FFFDF9] shadow-none"><CardContent className="p-6 md:p-9"><form onSubmit={submit} className="space-y-9">
 <div><Label>Foto de perfil</Label><div className="mt-3 flex items-center gap-5">{avatar?<div className="relative"><img src={avatar.preview} className="h-24 w-24 rounded-full object-cover" alt="Prévia"/><button type="button" onClick={()=>{URL.revokeObjectURL(avatar.preview);setAvatar(null)}} className="absolute -right-1 -top-1 rounded-full bg-[#0B3047] p-1 text-white"><X size={14}/></button></div>:<label className="flex h-24 w-24 cursor-pointer flex-col items-center justify-center rounded-full border-2 border-dashed border-[#D7D0C4] text-[#5E6870]"><ImagePlus size={20}/><span className="mt-1 text-[10px]">Adicionar</span><input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>pickAvatar(e.target.files?.[0])}/></label>}<p className="max-w-xs text-xs leading-5 text-[#5E6870]">Uma boa foto aumenta a percepção profissional.</p></div></div>
 <div className="grid gap-5 md:grid-cols-2"><Field label="Nome completo *" value={form.name} onChange={v=>set("name",v)}/><Field label="Profissão / especialidade *" value={form.title} onChange={v=>set("title",v)}/><Field label="Cidade / região *" value={form.city} onChange={v=>set("city",v)}/><Field label="WhatsApp *" value={form.phone} onChange={v=>set("phone",v)}/><Field label="E-mail *" type="email" value={form.email} onChange={v=>set("email",v)}/><Field label="Registro profissional" value={form.registration} onChange={v=>set("registration",v)}/></div>
 <Field label="LinkedIn" value={form.linkedin} onChange={v=>set("linkedin",v)} placeholder="linkedin.com/in/seu-nome"/><Field label="Frase de apresentação" value={form.headline} onChange={v=>set("headline",v)}/><div><Label>Sobre você</Label><Textarea className="mt-2 min-h-32" value={form.summary} onChange={e=>set("summary",e.target.value)} placeholder="Conte brevemente sobre sua experiência e atuação."/></div><div><Label>Competências</Label><Input className="mt-2" value={form.skills} onChange={e=>set("skills",e.target.value)} placeholder="Ex.: orçamento, obras, elétrica, projetos"/></div>
 <div className="border-t border-[#D7D0C4] pt-8"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><Label>Projetos do seu portfólio</Label><p className="mt-1 max-w-xl text-xs leading-5 text-[#5E6870]">Adicione cada trabalho como um projeto. Você pode colocar até 2 imagens por projeto.</p></div><span className="text-xs font-semibold text-[#F15A24]">{projects.length}/6 projetos</span></div>
 <div className="mt-5 space-y-5">{projects.map((p,i)=><div key={i} className="rounded-2xl border border-[#D7D0C4] bg-[#F5F1E9] p-5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 font-semibold"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#0B3047] text-xs text-white">{i+1}</span> Projeto</div>{projects.length>1&&<button type="button" onClick={()=>setProjects(x=>x.filter((_,j)=>j!==i))} className="text-xs font-semibold text-[#7b2d26]"><Trash2 size={15}/></button>}</div><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Nome do projeto" value={p.title} onChange={v=>updateProject(i,"title",v)}/><Field label="Localização" value={p.location} onChange={v=>updateProject(i,"location",v)}/></div><div className="mt-4"><Label>O que você fez neste projeto?</Label><Textarea className="mt-2 min-h-24 bg-[#FFFDF9]" value={p.description} onChange={e=>updateProject(i,"description",e.target.value)} placeholder="Ex.: projeto estrutural, orçamento, acompanhamento da execução..."/></div><div className="mt-4"><div className="flex items-center justify-between"><Label>Imagens <span className="font-normal text-[#5E6870]">(até 2)</span></Label><span className="text-xs text-[#5E6870]">{p.photos.length}/2</span></div><div className="mt-3 grid grid-cols-2 gap-3">{p.photos.map((x,j)=><div key={x.preview} className="relative aspect-[4/3] overflow-hidden rounded-xl bg-[#D9D2C4]"><img src={x.preview} alt="" className="h-full w-full object-cover"/><button type="button" onClick={()=>removePhoto(i,j)} className="absolute right-2 top-2 rounded-full bg-[#0B3047] p-1 text-white"><X size={14}/></button></div>)}{p.photos.length<2&&<label className="flex aspect-[4/3] cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-[#BEB5A6] text-[#5E6870]"><Upload size={20}/><span className="mt-2 text-xs">Adicionar imagem</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple className="hidden" onChange={e=>addPhotos(i,e.target.files)}/></label>}</div></div></div>)}</div>
 {projects.length<6&&<button type="button" onClick={addProject} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-[#BEB5A6] py-4 text-sm font-semibold hover:bg-[#F5F1E9]"><Plus size={17}/> Adicionar projeto</button>}</div>
 {error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{loading&&<p className="flex items-center gap-2 text-sm font-semibold"><span className="h-2 w-2 animate-pulse rounded-full bg-[#F15A24]"/>{progress||"Preparando..."}</p>}<Button type="submit" disabled={loading} className="w-full bg-[#F15A24] py-3">{loading?"Publicando...":"Criar meu perfil grátis"}</Button><p className="text-center text-xs leading-5 text-[#5E6870]">Ao publicar, você autoriza o Negócio Fechado a armazenar e exibir os dados profissionais informados nesta página.</p>
 </form></CardContent></Card></div></main>}
async function resizeImage(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext("2d");if(!ctx)return reject(new Error("Não foi possível processar a imagem."));ctx.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.72))};img.onerror=()=>reject(new Error("Imagem inválida."));img.src=String(reader.result)};reader.onerror=()=>reject(new Error("Não foi possível ler a imagem."));reader.readAsDataURL(file)})}
function Field({label,value,onChange,type="text",placeholder=""}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string}){return <div><Label>{label}</Label><Input type={type} className="mt-2" value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} required={label.includes("*")}/></div>}